version: "3"
services:
  ## Comment out `db` service if you're on Windows (not using WSL2) (no tmpfs support)
  ## See backend/src/main/resources/application.yml for details
  db:
    image: mysql/mysql-server:latest
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: spring
    tmpfs:
      - /var/lib/mysql

  backend:
    build: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    depends_on:
      - db
