version: "3"
services:
  db:
    image: mariadb:latest
    container_name: vax-warden-db
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: spring
    # NOTE: comment out tmpfs if you're on Windows (without WSL2) (no tmpfs support)
    # Also increase sleep time in backend/Dockerfile
    tmpfs:
      - /var/lib/mysql

  backend:
    build: backend
    container_name: vax-warden-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: frontend
      args:
        - BACKEND_HOST=localhost
        - BACKEND_PORT=8080
    container_name: vax-warden-frontend
    ports:
      - "443:3000"
    depends_on:
      - backend
