POST https://localhost:8080/auth/register
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "dateOfBirth": "2001-02-15",
  "ppsn": "1434527AB",
  "address": "UCD, Dublin 4, Co. Dublin, Ireland",
  "email": "jane.doe1@ucd.ie",
  "phoneNo": "0874795969",
  "nationality": "Ireland",
  "gender": "FEMALE",
  "password": "Admin!234"
}
