spring:
  application:
    name: backend

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: spring
    url: jdbc:mariadb://db:3306/hse?createDatabaseIfNotExist=true
    # url: jdbc:mariadb://localhost:3306/hse?createDatabaseIfNotExist=true

jwt_secret: NgHSMb5QkM+JPkZd7AiowzM0f5v5r3pYlqL3ltymWHawdxcun7ATNbgmu4BVMh8XOM/VTxYwU//WpA5V2PSogtGKakG+ynziCZ8JRfQYE9dTRaHgMr6Sk83X7Bwd1L3m6Y8mxzkke/MFJlgUViDwZa3pg9xhdBOei1dXrXxaBjJ0vGKBM5sv1qX4kJoQ2y4lo6kTlC9Y8nv9OzBW2iEOa1Dwmkzr5xlULjbykDX/cLIvzc+V7hPvWu/zutV14NPgv2lZ4MJ69Oi/GsirniFOPQuAXcCN66r2fOzeWqmE6v1KrHBFuTwL2ZQzVvTzcayJCqgKy7TVXpVnnLsA/wNCcQ==
