spring:
  application:
    name: backend

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: spring
    url: jdbc:mariadb://db:3306/hse?createDatabaseIfNotExist=true
    # url: jdbc:mariadb://localhost:3306/hse?createDatabaseIfNotExist=true
